# get api_id & api_hash from my.telegram.org
api_id: '15104173'
api_hash: '6aff375c0543375c5d5949d851dad72c'
# 13 digit channel id startswith - like -111.......
dump_id: '-1001805117102'
# genrate session of ur tg ac for telethon run sessionmaker.py
string_session: '1BVtsOLkBu2w4s1KgTxmtPITiVOh6s7tZrjx9WIrAWPPmFkrw3Kuyl-GcX_NsJ0_aQnc050MmBMoHeErMVO1ezTCl3lBmi9eSVMJkiJKl-Vg0ZbD_wnA6SoXE_tSBAr6cKaScINs-Od1uoh4w3-5sP-LxgNiYw-J4rwhiim5Aku9Yo7pq6Mh216VMfcRxAYZLY8F_IND1nHlbzlQGiw9YZ5paaRZW0_KIse5n-zkN4PZTPBJrh_3dvgM0k-zo-NjeU_MKLhwEdNikGxn73aNxGwK4QiHJb-AnwS3FANAD3v-E6ku5qA7ps1iTDrDP8MbPs393y_cwpLmWHgVyK-wbSBC-LpCNC3o='
